Add support for use as pre-commit hook
toy/image_optim pull request #192
Opened 2021-04-09 03:08 UTC by proinsias

2021-04-11 22:26 UTC, toy requested changes
Thanks for contribution.
Unfortunately looks like the action [failed](https://github.com/proinsias/image_optim/actions/runs/733127746).
Could you also please describe what is the action supposed to do? Check if version is up to date with what pre-commit knows as the latest version?

2021-04-11 22:26 UTC, toy commented on .github/workflows/actions.yml
> +on: [push, pull_request]
Are those good triggers?

2021-04-11 22:26 UTC, toy commented on .github/workflows/actions.yml
> +# yamllint disable-line rule:truthy
As there is no yamllint configured to run, I think this comment shouldn't be here

2021-04-11 22:26 UTC, toy commented on .github/workflows/actions.yml
> +        uses: browniebroke/pre-commit-autoupdate-action@v1.0.0
There seem to be a suggestion to create a PR after running this

2021-04-12 01:45 UTC, proinsias commented
@toy – thanks for the review. I believe I've addressed your comments. I realized I didn't need the GitHub Action as you're not using `pre-commit` for this repo itself.

2021-04-18 19:42 UTC, toy approved these changes

2021-04-18 19:46 UTC, toy commented
Thanks for finishing the PR :)
Travis is failing only because failing check on up to date rubies.
Seemed to work when installing from your fork and specifying commit sha for rev, do I understand right that it would be better to create a release (tag) for it to work nicely?

2021-04-18 19:47 UTC, merged

2021-04-28 18:45 UTC, toy commented
Created v0.29.0 tag